pluginManagement {
    repositories {
        gradlePluginPortal()
        mavenCentral()
    }
}

dependencyResolutionManagement {
    repositoriesMode.set(RepositoriesMode.FAIL_ON_PROJECT_REPOS)
    repositories {
        mavenCentral()
    }
}

rootProject.name = 'KOK'

include 'module'

include 'infrastructure:eureka-server'
include 'infrastructure:api-gateway'

include 'services:user-service'
include 'services:store-service'
include 'services:reservation-service'
include 'services:waiting-service'
include 'services:notification-service'