package com.omakase.kok.reservation.domain.enums;

public enum EventType {
    RESERVATION_CONFIRMED,
    RESERVATION_CANCELLED,
    RESERVATION_VISITED,
    RESERVATION_NO_SHOW,
    RESERVATION_CHANGED,
    RESERVATION_REMINDER_1DAY,
    RESERVATION_REMINDER_1HOUR
}
