server:
  port: ${NOTIFICATION_SERVICE_PORT:8005}

spring:
  application:
    name: notification-service

  datasource:
    url: ${NOTIFICATION_DB_URL:jdbc:postgresql://localhost:5433/notification_db}
    username: ${DB_USERNAME:postgres}
    password: ${DB_PASSWORD:postgres}
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: ${JPA_DDL_AUTO:update}
    properties:
      hibernate:
        format_sql: true
    open-in-view: false

  kafka:
    bootstrap-servers: ${KAFKA_BOOTSTRAP_SERVERS:localhost:9092}
    consumer:
      group-id: notification-service-group
      auto-offset-reset: earliest
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      enable-auto-commit: false

slack:
  bot-token: ${SLACK_BOT_TOKEN}

notification:
  retry:
    max-attempt-count: 3
    fixed-delay-ms: 300000  # 5분

feign:
  client:
    config:
      user-service:
        connectTimeout: 3000
        readTimeout: 3000

eureka:
  client:
    service-url:
      defaultZone: ${EUREKA_DEFAULT_ZONE:http://localhost:8761/eureka/}

management:
  endpoints:
    web:
      exposure:
        include: health,info